version: "3.3"

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: always

  db:
    image: postgres
    environment:
      - TZ=UTC
      - POSTGRES_DB=scrapers
      - POSTGRES_USER=scrapers_admin
      - POSTGRES_PASSWORD=fralDnewTw3w
    volumes:
      - .:/SiteSoftTests
    restart: always

  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/SiteSoftTests
    ports:
      - "8000:8000"
    depends_on:
      - db

    restart: always

  worker:
    build:
      context: .
    command: sh -c "celery -A config worker -B --concurrency=2 -l INFO"
    volumes:
      - .:/SiteSoftTests
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    restart: always


  flower:
      image: mher/flower
      restart: always
      command: ["celery", "flower", "--address=0.0.0.0", "--broker=CELERY_BROKER_URL","--port=5555", "--logging=DEBUG"]
      environment:
        CELERY_BROKER_URL: amqp://rabbitmq:5672
      depends_on:
        - rabbitmq
      ports:
        - 5555:5555
