# Generated by Django 4.0.5 on 2022-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostToScrapeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('scraped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=1024, null=True)),
                ('author_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('author_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('post_url', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='tags', to='posts.posttagmodel')),
            ],
        ),
    ]
