# Generated by Django 4.0.5 on 2022-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='posts.posttagmodel'),
        ),
    ]
