# Generated by Django 4.0.5 on 2022-06-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_postmodel_tags_posttagmodel_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttagmodel',
            name='post',
            field=models.ManyToManyField(related_name='tags', to='posts.postmodel'),
        ),
    ]
