# Generated by Django 4.0.5 on 2022-06-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posttagmodel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttagmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(to='posts.posttagmodel'),
        ),
    ]
